### ISSUE TITLE
vegdist with EcoPlate

### ISSUE THREAD

**Issue by mmuscarella** [LennonLab/StarvationTraits#14]
@jaytlennon: I'm confused about your analysis. You are making a distance matrix from the EcoPlate data. However, this is not a site-by-species matrix or any other data matrix that can be used to make a resemblance matrix. So, I'm a bit confused. If you look at the distance matrix you will see the issue (it is looking at the resemblance of rows based on columns (not appropriate).

**Comment by jaytlennon** [comment]
yeah, good points
